config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resources :sessions, only: %i[new create destroy]

  resources :questions, except: %i[show new index], shallow: true do
    resources :hashtags, only: %i[show]
  end

  get 'sign_up' => 'users#new'
  get 'log_out' => 'sessions#destroy'
  get 'log_in' => 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  LINE = /#[[:word:]]+/.freeze

  has_many :hashtag_questions, dependent: :destroy
  has_many :questions, through: :hashtag_questions

  validates :name, presence: true, uniqueness: true, format: { with: LINE }, length: { maximum: 20 }

  before_validation :downcase_tag

  def downcase_tag
    name&.downcase!
  end
end

app/models/hashtag_question.rb
class HashtagQuestion < ApplicationRecord
  belongs_to :question
  belongs_to :hashtag
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :hashtag_questions, dependent: :destroy
  has_many :hashtags, through: :hashtag_questions

  validates :text, length: { maximum: 255 }

  scope :sorted, -> { order(created_at: :desc) }

  after_save :save_hashtags
  after_destroy :delete_old_tags

  private

  def save_hashtags
    self.hashtags = find_patterns.map { |name| Hashtag.find_or_create_by(name: name.downcase) }
  end

  def find_patterns
    answer_tags =  answer&.scan(Hashtag::LINE) || []
    text.scan(Hashtag::LINE) | answer_tags
  end

  def delete_old_tags
    Hashtag.left_outer_joins(:questions).where(questions: { id: nil }).destroy_all
  end
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  ITERATIONS = 20_000
  DIGEST = OpenSSL::Digest.new('SHA256')
  EMAIL_FORMAT = /\A\w+@\w+\.[a-z]+\z/.freeze
  USERNAME_FORMAT = /\A\w+\z/.freeze
  COLOR = /\A#\h{6}\z/.freeze

  attr_accessor :password

  has_many :questions, dependent: :destroy

  validates :password, presence: true, on: :create
  validates :password, confirmation: true
  validates :username, :email, presence: true, uniqueness: true
  validates :username, length: { maximum: 40 }
  validates :email, format: { with: EMAIL_FORMAT }
  validates :username, format: { with: USERNAME_FORMAT }
  validates :header_color, format: { with: COLOR }

  before_validation :normalize_username, :normalize_email
  before_save :encrypt_password

  def self.hash_to_string(password_hash)
    password_hash.unpack1('H*')
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    return nil if user.blank?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )

    return user if user.password_hash == hashed_password

    nil
  end

  private

  def normalize_username
    username&.downcase!
  end

  def normalize_email
    email&.downcase!
  end

  def encrypt_password
    return if password.blank?

    self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

    self.password_hash = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find(params[:id])
    @questions = @hashtag.questions.distinct
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  helper_method :question

  before_action :authorize_user, except: [:create]

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if question.save
      redirect_to user_path(question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  def update
    if question.update(question_params)
      redirect_to user_path(question.user), notice: 'Вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    question.destroy
    redirect_to user_path(question.user), notice: 'Вопрос удален :('
  end

  private

  def authorize_user
    reject_user unless question.user == current_user
  end

  def question
    @question ||= params[:id].present? ? Question.find(params[:id]) : Question.new
  end

  def question_params
    if params[:question][:user_id].to_i == current_user&.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный мэйл или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to root_path, notice: 'Вы разлогинились! Приходите еще!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  helper_method :user

  before_action :authorize_user, only: %i[edit destroy update]

  def index
    @users = User.all
    @hashtags = Hashtag.all
  end

  def new; end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Пользователь успешно зарегистрирован!'
    else
      render :new
    end
  end

  def show
    @questions = user.questions.sorted
    @questions_count = @questions.length
    @answered_questions_count = @questions.where.not(answer: nil).count
    @unanswered_questions_count = @questions_count - @answered_questions_count
    @new_question = user.questions.build
  end

  def edit; end

  def update
    if user.update(user_params)
      redirect_to user_path(user), notice: 'Данные обновлены'
    else
      render :edit
    end
  end

  def destroy
    user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Профиль удален, приходите еще!'
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username,
                                 :avatar_url,
                                 :header_color)
  end

  def user
    @user ||= params[:id].present? ? User.find(params[:id]) : User.new
  end

  def authorize_user
    reject_user unless user == current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hashtags/_hashtag.html.slim
span.tag.is-link.is-medium.mr-2
  = link_to hashtag.name, hashtag_path(hashtag), class: 'has-text-white'

app/views/hashtags/show.html.slim
h1.has-text-white= "Вопросы с хештегом #{@hashtag.name}"
= render partial: 'questions/question', collection: @questions

app/views/layouts/application.html.slim
doctype html
html
  head
    title Askme
    meta content="width=device-width,initial-scale=1" name="viewport"
    meta charset="UTF-8"
    title Хорошие вопросы
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_pack_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
  body
    .header
      .container
        .header-logo
          h1.header-title= link_to 'Хорошие вопросы', root_path

        .header-nav
          - if current_user
            = link_to "#{current_user.username}", user_path(current_user)
            = link_to 'Выйти', log_out_path, class: 'button-logout'
          - else
            = link_to 'Зарегистрироваться', sign_up_path, class: 'button button-light button-small'
            = link_to 'Войти', log_in_path, class: 'button button-light button-small'

    .content
      .container
        - if flash.any?
          .content-wrapper.buffer-both
          -flash.each do |name, message|
            = content_tag :div, message, class: "flash-#{name}"

        = yield

app/views/questions/_form.html.slim
.form
  = form_for question do |f|
    =render 'shared/errors', resource: question

    =f.hidden_field :user_id

    .form-field
      = f.label :text, 'Вопрос', class: 'form-label'
      = f.text_area :text, class: 'form-textarea'

    -if current_user.present? && current_user == question.user
      .form-field
        = f.label :answer, 'Ответ', class: 'form-label'
        = f.text_area :answer, class: 'form-textarea'

    .form-action.buffer-both
      = f.submit 'Сохранить', class: 'button button-dark button-small'
      = link_to "Вернуться", users_path

app/views/questions/_question.html.slim
.question
  .question-content
    .question-text.text-lead
      = question.text

    -if question.answer.present?
      .question-answer.text-lead
        = question.answer

    .question-date
      = question.decorate.normalize_date

    /or uniq
    = render partial: 'hashtags/hashtag', collection: question.hashtags.distinct

  -if question.user == current_user
    .question-actions
      = link_to edit_question_path(question)
        = content_tag(:i, '', class: "#{question.decorate.action_icon}")
      = link_to question_path(question), method: :delete, data: {confirm: 'Точно удалить вопрос?'}
        i.fas.fa-trash-alt

  = question.decorate.author_link

app/views/questions/edit.html.slim
.container.content-wrapper.buffer-both
  h1.title-medium Вопрос

  .column-1-2
    = render 'form'

app/views/shared/_errors.html.slim
- if resource.errors.any?
  .form-errors
    ul
      -resource.errors.full_messages.each do |message|
        li.form-error-message= message

app/views/users/_form.html.slim
.column-1-2
  = form_for user do |f|
    = render 'shared/errors', resource: user
    .form-field
      = f.label :header_color, 'Цвет шапки', class: 'form-label'
      = f.color_field :header_color

    .form-field
      = f.label :email, 'Логин (email)', class: 'form-label'
      = f.text_field :email, class: 'form-text-field'

    .form-field
      = f.label :username, 'Никнейм', class: 'form-label'
      = f.text_field :username, class: 'form-text-field'

    .form-field
      = f.label :name, 'Имя', class: 'form-label'
      = f.text_field :name, class: 'form-text-field'

    .form-field
      = f.label :password, 'Пароль', class: 'form-label'
      = f.password_field :password, class: 'form-text-field'

    .form-field
      = f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label'
      = f.password_field :password_confirmation, class: 'form-text-field'

    .form-action
      = f.submit 'Отправить', class: 'button button-small button-dark'

app/views/users/edit.html.slim
.container.content-wrapper.buffer-both
  h1.title-medium Править профиль

  .buffer-top-large.buffer-bottom Если не хотите менять пароль — оставьте поля пустыми!
  =render 'form'

app/views/users/index.html.slim
.content-wrapper.buffer-both.text-center
  .buffer-both
    h1.title-medium Наши пользователи

    -@users.each do |user|
      .users-list-item
        .user-image-div.user-image-div-small
          =link_to image_pack_tag('avatar.jpg', class: 'user-image'), user_path(user)

= render partial: 'hashtags/hashtag', collection: @hashtags

app/views/users/new.html.slim
.container.content-wrapper.buffer-both
  .h1.title-medium Присоединяйся к нам!

  .column-1-2
    = form_for user do |f|
      = render 'shared/errors', resource: user
      .form-field
        = f.label :email, 'Логин (email)', class: 'form-label'
        = f.text_field :email, class: 'form-text-field'

      .form-field
        = f.label :username, 'Никнейм', class: 'form-label'
        = f.text_field :username, class: 'form-text-field'

      .form-field
        = f.label :password, 'Пароль', class: 'form-label'
        = f.password_field :password, class: 'form-text-field'

      .form-field
        = f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label'
        = f.password_field :password_confirmation, class: 'form-text-field'

      .form-action
        = f.submit 'Отправить', class: 'button button-small button-dark'

app/views/users/show.html.slim
.user-header.text-center style="background: #{user.header_color}"
  h1.title-medium
    = user.username

  .buffer-both
  - if current_user == user
    = link_to 'Редактировать профиль', edit_user_path(user)
    p
      = link_to 'Удалить профиль', user_path(user), method: :delete, data: { confirm: 'Вы уверены?' }

  .user-image-div
    = image_pack_tag('avatar.jpg', class: 'user-image', alt: '[Фото]')

  h2.title-small.buffer-both
    .count-info
      p= t('.questions_count', count: @questions_count)
      p= t('.answered_questions', count: @answered_questions_count)
      -unless @unanswered_questions_count.zero?
        p= t('.unanswered_questions', count: @unanswered_questions_count)

  .user-ask-button.container.text-center
    = link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button'

.user-question-form-div.column-1-4.column-1-4-right id='ask-form'
  .user-question-form.buffer-both

    .form
      = form_for @new_question do |f|
        = f.hidden_field :user_id
        .form-field
          = f.label "Ваш вопрос для #{user.username}", class: 'form-label'
          = f.text_area :text, class: 'form-textarea'

        .form-action
          = submit_tag 'Задать вопрос', class: 'button button-small button-dark'

.column-3-4
  .user-questions.buffer-both
    .questions-list
      - @questions.each do |question|
        = render partial: 'questions/question', object: question